# Generated by Django 3.2.4 on 2022-03-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=13)),
                ('nombre_completo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
    ]
