# Generated by Django 3.2.4 on 2022-03-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=45)),
                ('fecha_elaboracion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_numero_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.factura')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=1)),
                ('descuentos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.descuentos')),
                ('factura_numero_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='impuestos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_factura.impuestos'),
        ),
    ]
