# Generated by Django 3.2.4 on 2022-03-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0002_auto_20220317_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identidad',
            field=models.IntegerField(max_length=13),
        ),
    ]
