# Generated by Django 3.2.4 on 2022-03-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_factura', '0004_alter_cliente_identidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuestos',
            name='telefono',
        ),
    ]
